---
title: "Chapter 3"
subtitle: "Statistical Rethinking"
format: html
---

## R code 3.1

```{r}
Pr_Positive_Vampire <- 0.95
Pr_Positive_Mortal <- 0.01
Pr_Vampire <- 0.001
Pr_Positive <- Pr_Positive_Vampire * Pr_Vampire + Pr_Positive_Mortal * (1 - Pr_Vampire)
(Pr_Vampire_Positive <- Pr_Positive_Vampire * Pr_Vampire / Pr_Positive)
```
## R code 3.2

```{r}
p_grid <- seq(from=0, to=1, length.out=1000)
prob_p<- rep(1, 1000)
prob_data <- dbinom(6, size=9, prob=p_grid)
posterior <- prob_data * prob_p
posterior <- posterior / sum(posterior)
```
## R code 3.3

```{r}
samples <- sample(p_grid, prob=posterior, size=1e4, replace=TRUE)
```
## R code 3.4

```{r}
plot(samples)
```
## R code 3.5

```{r}
library(rethinking)
dens(samples)
```
## R code 3.6

```{r}
sum(posterior[p_grid<0.5])
```
## R code 3.7

```{r}
sum(samples < 0.5) / 1e4
```
## R code 3.8

```{r}
sum(samples > 0.5 & samples < 0.75) / 1e4
```
## R code 3.9

```{r}
quantile(samples, 0.8)
```
## R code 3.10

```{r}
quantile(samples, c(0.1, 0.9))
```
## R code 3.11

```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 )
prior <- rep(1,1000)
likelihood <- dbinom( 3 , size=3 , prob=p_grid )
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)
samples <- sample( p_grid , size=1e4 , replace=TRUE , prob=posterior )
```
## R code 3.12

```{r}
PI(samples, prob=0.5)
```
## R code 3.13

```{r}
HPDI(samples, prob=0.5)
```
## R code 3.14

```{r}
p_grid[which.max(posterior)]
```
## R code 3.15

```{r}
chainmode(samples, adj=0.01)
```
## R code 3.16

```{r}
mean(samples)
median(samples)
```
## R code 3.17

```{r}
sum(posterior*abs(0.5-p_grid))
```
## R code 3.18

```{r}
loss <- sapply(p_grid, function(d) sum(posterior*abs(d-p_grid)))
```
## R code 3.19

```{r}
p_grid[which.min(loss)]
```
## R code 3.20

```{r}
dbinom(0:2, size=2, prob=0.7)
```
## R code 3.21

```{r}
rbinom(1, size=2, prob=0.7)
```
## R code 3.22

```{r}
rbinom(10, size=2, prob=0.7)
```
## R code 3.23

```{r}
dummy_w <- rbinom(1e5, size=2, prob=0.7)
table(dummy_w)/1e5
```
## R code 3.24

```{r}
dummy_w <- rbinom(1e5, size=9, prob=0.7)
simplehist(dummy_w, xlab="dummy water count")
```
## R code 3.25

```{r}
w <- rbinom(1e4, size=9, prob=0.6)
```
## R code 3.26

```{r}
w <- rbinom(1e4, size=9, prob=samples)
```